//===----------------------------------------------------------------------===//
//                         DuckDB
//
// core_functions/aggregate/llm_functions.hpp
//
//
//===----------------------------------------------------------------------===//
// This file is automatically generated by scripts/generate_functions.py
// Do not edit this file manually, your changes will be overwritten
//===----------------------------------------------------------------------===//

#pragma once

#include "duckdb/function/function_set.hpp"

namespace duckdb {

struct LlmAggFun {
	static constexpr const char *Name = "llmAgg";
	static constexpr const char *Parameters = "prompt,arg";
	static constexpr const char *Description = "Returns a string aggregated from a LLM.";
	static constexpr const char *Example = "llmAgg(A)";
	static constexpr const char *Categories = "";

	static AggregateFunction GetFunction();
};

} // namespace duckdb
